controller_manager:
  ros__parameters:
    update_rate: 200  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - joint1
      - joint2
    #interface_name: effort  # Importante: actúa con torques
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      joint1:
        p: 72.0  # Por Zn
        i: 500.0
        d: 1.35
        i_clamp: 5.0
        antiwindup: true
      joint2:
        p: 54.0   # Por ZN
        i: 100.0
        d: 0.4
        i_clamp: 10.0
        antiwindup: true
